Numpy
- Numpy is scientific computing and mathematic library
- We will use to generate som arrays or matrices of data

In [1]:
import numpy as np

In [2]:
myList = [2, 4, 6, 8]
type(myList)

list

In [3]:
myArray = np.array(myList)
type(myArray)

numpy.ndarray

In [4]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b = np.arange(0, 10, 2)
b

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros((1, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((2, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
type(1.0)

float

In [11]:
type(1.)

float

In [12]:
np.random.randint(0, 100)

32

In [13]:
np.random.randint(0, 100)

8

In [14]:
np.random.randint(0, 100, (3, 3))

array([[48, 96, 24],
       [35, 29, 38],
       [18, 43, 73]])

In [15]:
np.linspace(0,10,6) # linspace provides data with same space

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [16]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [17]:
np.random.seed(101) # use same seed, we will get same random data

In [18]:
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [19]:
np.random.randint(0,100,10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [20]:
arr = np.random.randint(0,100,10)
arr

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [21]:
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.argmin()) # give a lication/index of data
print(arr.argmax())
print(arr.reshape(2, 5))

40.7
8
83
2
1
[[49 83  8 29 59]
 [34 44 72 19 10]]


In [22]:
mat = np.arange(0, 100)
mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
mat.reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
mat > 50 # Mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [25]:
mat[mat > 50] # apply Mask

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
import pandas as pd

In [27]:
df = pd.DataFrame({'column_a': [1, 3, np.nan, 7, 9], 'column_b': [np.nan, 4, 6, 8,10]}) # use dictionary and mumpy to create dataframe's data

In [28]:
df

column_a  column_b
0       1.0       NaN
1       3.0       4.0
2       NaN       6.0
3       7.0       8.0
4       9.0      10.0

In [29]:
df = pd.DataFrame([i for i in range(5)], columns = ['column_a'], index = pd.date_range('2023-01-01', periods = 5))
df

column_a
2023-01-01         0
2023-01-02         1
2023-01-03         2
2023-01-04         3
2023-01-05         4