## Python Libraries for Data Science
- Pandas
- Matplotlib
- SciPy
- NumPy:
   - Written monstly in C => Complied mathemetical and numerical functions guarantee great execution speed
   - Powerful data structures: 
      - Multi-dimensional arrays and matrices
      - Vectorized computation

In [2]:
import numpy as np

### Python list vs Numpay Array

- List: Can use different datatype in a list
- Numpy Array: accept only same datatype (Must be of the same)

In [3]:
alist = ['Mark', 93, "Bam", 1.95]
alist

['Mark', 93, 'Bam', 1.95]

In [4]:
list_a = list(range(20))
list_a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [5]:
type(list_a)

list

In [6]:
# add all data in list a with 5 require loop

for num in range(len(list_a)):
    list_a[num] += 5
list_a

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

In [7]:
array_a = np.arange(20)
array_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
type(array_a)

numpy.ndarray

In [9]:
# add all data in an array doesn't need to use loop, just add it

array_a = array_a + 5 
array_a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [10]:
# find log base 2 of all even number between 10

even_num = list(range(2, 11, 2)) # here we work as a list of range (start, stop, range)
even_num

[2, 4, 6, 8, 10]

In [11]:
even = np.arange(2, 11, 2) # here we work as NumPy array (start, stop, range)
even

array([ 2,  4,  6,  8, 10])

In [12]:
even_log2 = np.log2(even)
even_log2

array([1.        , 2.        , 2.5849625 , 3.        , 3.32192809])

In [13]:
# fotmat beautiful 3 digits

for i, logi in zip(even, even_log2):
    print(f"{i}\t{logi:.3f}")

2	1.000
4	2.000
6	2.585
8	3.000
10	3.322


In [14]:
print("i\tlog(i)")
for i, logi in zip(even, even_log2):
    print(f"{i}\t{logi:.3f}")

i	log(i)
2	1.000
4	2.000
6	2.585
8	3.000
10	3.322


In [15]:
# Axis

data = np.array([[1, 3, 6, 9], [0, 39, 12, 5], [4, 2, 6, 3], [85, 33, 2, 60]])
data

array([[ 1,  3,  6,  9],
       [ 0, 39, 12,  5],
       [ 4,  2,  6,  3],
       [85, 33,  2, 60]])

In [16]:
data.min(axis = 0) # column wise

array([0, 2, 2, 3])

In [17]:
data.min(axis = 1) # row wise

array([1, 0, 2, 2])

### Broadcasting
- NumPy arrays can be broadcast against each other if their dimensions match orif one of the array has a size of 1
- คือถ้า array ไม่เท่ากันก็เอามาบอก ลบ ได้

In [18]:
import numpy as np

a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
a.shape

(16,)

In [20]:
b = np.arange(16).reshape(4, 4) # 4x4
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
b.shape

(4, 4)

In [22]:
c = np.arange(8).reshape(2, 4)
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
c.shape

(2, 4)

In [24]:
b + c

ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 

In [25]:
d = np.arange(4).reshape(1, 4)
d

array([[0, 1, 2, 3]])

In [26]:
c + d

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10]])

In [27]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
b[0,:]

array([0, 1, 2, 3])

In [29]:
b[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
b[2,:]

array([ 8,  9, 10, 11])

In [31]:
b[2, 2:3]

array([10])

In [32]:
b[2, 1:3]

array([ 9, 10])

In [33]:
b[2:, 2:]

array([[10, 11],
       [14, 15]])

In [34]:
b[0, :]

array([0, 1, 2, 3])

In [35]:
b[0, :].sum()

6

In [36]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
b.sum()

120

In [38]:
b[2:, 2:]

array([[10, 11],
       [14, 15]])

In [39]:
b[2:, 2:].max()

15

In [40]:
b[2:, 2:].min()

10

In [41]:
b[2:, 2:].mean()

12.5

In [42]:
b.min(axis = 0)

array([0, 1, 2, 3])

In [43]:
b.min(axis = 1)

array([ 0,  4,  8, 12])

In [44]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
b.shape

(4, 4)

In [46]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
c.shape

(2, 4)

In [48]:
c.sum(axis = 0) # column wise

array([ 4,  6,  8, 10])

In [50]:
c.sum(axis = 1) # row wise

array([ 6, 22])

In [59]:
# Masking

nums = np.linspace(1, 25, 5, dtype = float)
nums

array([ 1.,  7., 13., 19., 25.])

In [60]:
nums % 2 == 0

array([False, False, False, False, False])

In [61]:
nums % 3 == 0

array([False, False, False, False, False])

In [62]:
nums % 19 == 0

array([False, False, False,  True, False])

In [63]:
numbers = np.linspace(1, 50, 10, dtype = int)
numbers

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [64]:
numbers % 2 == 0

array([False,  True, False, False,  True,  True, False, False,  True,
        True])

In [65]:
numbers % 3 == 0

array([False,  True, False, False, False, False,  True,  True, False,
       False])

In [66]:
condition1 = numbers % 3 == 0
condition1

array([False,  True, False, False, False, False,  True,  True, False,
       False])

In [68]:
numbers[condition1] # get number which condition1 = True

array([ 6, 33, 39])