## Python Libraries for Data Science
- Pandas
- Matplotlib
- SciPy
- NumPy:
   - Written monstly in C => Complied mathemetical and numerical functions guarantee great execution speed
   - Powerful data structures: 
      - Multi-dimensional arrays and matrices
      - Vectorized computation

In [45]:
import numpy as np

### Python list vs Numpay Array

- List: Can use different datatype in a list
- Numpy Array: accept only same datatype (Must be of the same)

In [46]:
alist = ['Mark', 93, "Bam", 1.95]
alist

['Mark', 93, 'Bam', 1.95]

In [47]:
list_a = list(range(20))
list_a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [48]:
type(list_a)

list

In [49]:
# add all data in list a with 5 require loop

for num in range(len(list_a)):
    list_a[num] += 5
list_a

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

In [50]:
array_a = np.arange(20)
array_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
type(array_a)

numpy.ndarray

In [52]:
# add all data in an array doesn't need to use loop, just add it

array_a = array_a + 5 
array_a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [53]:
# find log base 2 of all even number between 10

even_num = list(range(2, 11, 2)) # here we work as a list of range (start, stop, range)
even_num

[2, 4, 6, 8, 10]

In [54]:
even = np.arange(2, 11, 2) # here we work as NumPy array (start, stop, range)
even

array([ 2,  4,  6,  8, 10])

In [55]:
even_log2 = np.log2(even)
even_log2

array([1.        , 2.        , 2.5849625 , 3.        , 3.32192809])

In [56]:
# fotmat beautiful 3 digits

for i, logi in zip(even, even_log2):
    print(f"{i}\t{logi:.3f}")

2	1.000
4	2.000
6	2.585
8	3.000
10	3.322


In [57]:
print("i\tlog(i)")
for i, logi in zip(even, even_log2):
    print(f"{i}\t{logi:.3f}")

i	log(i)
2	1.000
4	2.000
6	2.585
8	3.000
10	3.322


In [67]:
# Axis

data = np.array([[1, 3, 6, 9], [0, 39, 12, 5], [4, 2, 6, 3], [85, 33, 2, 60]])
data

array([[ 1,  3,  6,  9],
       [ 0, 39, 12,  5],
       [ 4,  2,  6,  3],
       [85, 33,  2, 60]])

In [68]:
data.min(axis = 0) # column wise

array([0, 2, 2, 3])

In [69]:
data.min(axis = 1) # row wise

array([1, 0, 2, 2])

### Broadcasting
- NumPy arrays can be broadcast against each other if their dimensions match orif one of the array has a size of 1
- คือถ้า array ไม่เท่ากันก็เอามาบอก ลบ ได้