In [1]:
# import a library

import numpy as np

In [2]:
# create metrics

m = np.array([[5, 12, 7], [-4, 0, 6]])
m

array([[ 5, 12,  7],
       [-4,  0,  6]])

In [3]:
type(m)

numpy.ndarray

In [4]:
m.shape

(2, 3)

In [5]:
# transpose metrices

m.T

array([[ 5, -4],
       [12,  0],
       [ 7,  6]])

In [6]:
mT = m.T

In [7]:
mT.shape

(3, 2)

In [9]:
# transpose scalar

s = np.array([10])
s

array([10])

In [10]:
type(s)

numpy.ndarray

In [11]:
s.shape

(1,)

In [12]:
sT = s.T
sT

array([10])

In [13]:
# transpose vector

v = np.array([1, 3, 5, 7])
v

array([1, 3, 5, 7])

In [14]:
type(v)

numpy.ndarray

In [15]:
v.shape

(4,)

In [16]:
vT = v.T
vT

array([1, 3, 5, 7])

In [17]:
vT.shape # cannot tranpose, we require reshape() function then applay T to transpose

(4,)

In [18]:
v_reshaped = v.reshape(1, 4)
v_reshaped

array([[1, 3, 5, 7]])

In [19]:
v_reshaped.shape

(1, 4)

In [20]:
v_reshaped.T

array([[1],
       [3],
       [5],
       [7]])