In [21]:
# create tuple

tuple_a = ([1, 3, 5, 7, 9], ['BamBam', "Mark", "Jackson"])
tuple_a

([1, 3, 5, 7, 9], ['BamBam', 'Mark', 'Jackson'])

In [22]:
type(tuple_a)

tuple

In [23]:
tuple_a[1]

['BamBam', 'Mark', 'Jackson']

In [24]:
tuple_a[1][2]

'Jackson'

In [25]:
tuple_a[1][2] = "JB"
tuple_a

([1, 3, 5, 7, 9], ['BamBam', 'Mark', 'JB'])

In [26]:
tuple_a

([1, 3, 5, 7, 9], ['BamBam', 'Mark', 'JB'])

In [27]:
# slicing

tuple_a[-1]

['BamBam', 'Mark', 'JB']

In [28]:
tuple_a[-1][:1]

['BamBam']

In [29]:
tuple_a[-1][:2]

['BamBam', 'Mark']

In [30]:
tuple_a[0][:1]

[1]

In [31]:
tuple_a[0][:-1:2]

[1, 5]

In [32]:
tuple_a[1] = 0

TypeError: 'tuple' object does not support item assignment

In [33]:
# we cannot reassign data to a tuple but we can reassign data to list in that tuple

In [34]:
# create list

list_a = [[1, 3, 5, 7, 9], ['BamBam', "Mark", "Jackson"]]
list_a

[[1, 3, 5, 7, 9], ['BamBam', 'Mark', 'Jackson']]

In [35]:
type(list_a)

list

In [36]:
list_a[0]

[1, 3, 5, 7, 9]

In [37]:
list_a[1]

['BamBam', 'Mark', 'Jackson']

In [38]:
list_a[1][1]

'Mark'

In [39]:
list_a[1][0] = "Jinyoung"

In [40]:
list_a

[[1, 3, 5, 7, 9], ['Jinyoung', 'Mark', 'Jackson']]

In [41]:
list_a[0][::2]

[1, 5, 9]

In [42]:
list_a[1] = 0
list_a

[[1, 3, 5, 7, 9], 0]

In [43]:
sum(list_a[0])

25

In [44]:
min(list_a[0])

1

In [45]:
max(list_a[0])

9

In [47]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [48]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



In [49]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [50]:
# function from library

import numpy as np

In [51]:
n = np.random.randn(10)
n

array([ 1.33575387,  0.39460817,  0.34434795,  0.11920276, -1.05252976,
        1.38412971,  0.54647976,  0.06427912, -1.43853437,  0.01946639])

In [52]:
np.sum(n)

1.717203602245768

In [53]:
np.mean(n)

0.1717203602245768

In [54]:
np.linspace(1, 4, 5) # to return a linear line from 1 to 4 with 5 number

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [56]:
lin = np.linspace(1, 4, 5)
lin

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [57]:
type(lin)

numpy.ndarray

In [58]:
# so we can apply numpy function of array

np.max(lin)

4.0

In [59]:
np.mean(lin)

2.5